### ISSUE TITLE
collaboration, checklists, life, etc

### ISSUE THREAD

**Issue by cauerego** [m-i-n-a-r/randomix#13]
hey there minar from italy!

cregox from portugal here.

this should probably be an email but I generally prefer to speak in public, so please bear with me.

- first of all, how about instead of keeping reinventing the wheel, collaborating with other open source projects that already exist, such as gear61 https://github.com/Gear61/Random-Number-Generator/issues/47 ? this point is actually a double point.
- if I was going to build a checklist for things that are needed in such an app, we would get a lot of issues in this one. wait in fact I have built a minor checklist: https://cregox.net/caxanga
- I'm bringing those points because I identify a lot with you, like I do with a lot of other coders. I mean at least myself around 15 years ago. at this point I just want to keep it short and tell you: there's a lot more to life than what I can see in your eyes right now.
- to reinforce the first double point, and randomness in general (in fact serendipity is all around this message), you might want to keep in mind that randomness and chaos are so much bigger than just being unpredictable. in fact the java pseudo random number generator you use here is not even that unpredictable at all.

above all, thanks for doing this little nice app and making it open and free!

it did trigger my curious quest today, and I do appreciate it. in a way it was thanks to you.

I know this all sounds crazy. that's because it is.

cheers. 😘

**Comment by m-i-n-a-r** [comment]
Hi there, thanks for taking the time to write:
- I wasn't interested in contributing to the open source world when i started Randomix, in 2016. It was my first Android App (even if i develop Themes and other stuff since 2012) and that's the reason why it's written in Java (i use Kotlin now, which is way better). Only after some time i decided to publish it, simply because there was no way to make money on it (yep i'm being super honest).
- For the same reason, my only purpose was to learn end experiment with animated vector drawables, without offering something super professional. Of course, i appreciate your suggestion!
- I'm now working on other projects and i only mantain Randomix when i'm free from work and other apps (here on Github i published Birday for example), and i understand that this is just a starting point which i shared with other beginners 😄 
- I know that the random number generator used in Java is not umpredictable, but since we're talking of a utility app, i thought that it was enough. Surely it can't be used to encrypt stuff!

I'm glad you like the app, i'm still thinking of possible improvements even if, as i said, it's not my priority.

Have a great day! 😃

**Comment by cauerego** [comment]
you'll probably want to close this non-issue then. so i'll do it for you.

hope you'll eventually be able to give this quest more love!

and thank you for the reply!! 🥰
